---
abstract: 'HTTP server can encrypt BODY section'
author:
  - 'ChenGang <yikuyiku.com@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Encrypt
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::CBC: 0
  Data::Dump: 0
  Digest::MD5: 0
  HTTP::Date: 0
  HTTP::Status: 0
  LWP::MediaTypes: 0
  LWP::UserAgent: 0
  Log::Lite: 0.03
  MIME::Base64: 0
  Sys::Sendfile: 0
version: 0.11
